#################### default parameters ################################
# favicon module: https://github.com/gethugothemes/hugo-modules/tree/master/images#favicon-implementation
favicon = "images/favicon.png"
# logo module: https://github.com/gethugothemes/hugo-modules/tree/master/images#logo-implementation
logo = "images/logo.png"
logo_darkmode = "images/logo-darkmode.png"
# use `px` or `x` with logo_width, example: "100px".
logo_width = "120px"
logo_height = "24px"
# if logo_webp set false, will not generate WEBP version of logo | default is true
logo_webp = true
# logo text will only show when logo is missing.
logo_text = "Charmtop"
# navbar fixed to top
navbar_fixed = true
# theme-mode
theme_switcher = true
theme_default = "light" # changed from "system" to "light"
# Main Sections
mainSections = ["blog"]
# Summary length settings
summary_length = 120
chinese_summary_length = 600  # Updated Chinese summary length
# contact form action
contact_form_action = "#"
# contact form works with [https://airform.io/] or [https://formspree.io]
# google tag manager, see https://developers.google.com/tag-manager/
google_tag_manager = "GTM-526D9M9S" # Google Tag Manager ID
google_adsense = ""     # example: ca-pub-xxxxxxxxxxxxxxxx
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>"
custom_script = ""
# copyright
copyright = "Powered by [Charmtop Consultants](https://www.charmtop.com.hk)"

# Author information
[params.author]
  name = "Charmtop Consultants"
  image = "images/author.jpg"
  bio = "Professional consultancy services"
  email = "info@charmtop.com.hk"

# Social links
[params.social]
  twitter = "https://twitter.com/charmtop"
  linkedin = "https://linkedin.com/company/charmtop"
  facebook = "https://facebook.com/charmtop"
  instagram = "https://instagram.com/charmtop"

# Preloader
# preloader module: https://github.com/gethugothemes/hugo-modules/tree/master/components/preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Contact Us"
link = "contact"

# search
# search module: https://github.com/gethugothemes/hugo-modules/tree/master/search
[search]
enable = true
primary_color = "#121212"
include_sections = ["blog"]
show_image = true
show_description = true
show_tags = true
show_categories = true

# announcement
# announcement module: https://github.com/gethugothemes/hugo-modules/tree/master/components/announcement
[announcement]
enable = false
expire_days = 7
content = "You must replace the **baseURL** in **hugo.toml** file when deploying, you can manage this announcement from the **params.toml** file."

# seo meta data for OpenGraph / Twitter Card
# seo module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/basic-seo
[metadata]
keywords = ["Charmtop", "weak electricity", "system integrator"]
description = "Charmtop Consultants"
author = "Charmtop"
image = "images/og-image.png"


# site verifications
# verification module: https://github.com/gethugothemes/hugo-modules/tree/master/seo-tools/site-verifications
[site_verification]
google = ""   # Your verification code
bing = ""     # Your verification code
baidu = ""    # Your verification code
facebook = "" # Your verification code
mastodon = "" # Your verification code

# cookies
# cookies module: https://github.com/gethugothemes/hugo-modules/tree/master/components/cookie-consent
[cookies]
enable = false
expire_days = 60
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# diagrams
[mermaid]
js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs'

######################## sidebar widgets #########################
[widgets]
sidebar = ["categories", "tags"]

# google map
[google_map]
enable = true
map_api_key = "AIzaSyB_RobNJzyLG0kZlkpcNsjPx4QN07I4n3M"
map_latitude = "22.284911309837845"
map_longitude = "114.15032180669813"
map_marker = "images/marker.png"
map_id = "8f51c45b7cd9a219"

# Remove redundant params section
[params]
google_map_js_path = "themes/hugoplate/assets/plugins/maps/google-map.js"
# Disable the avatar/circle
[params.sidebar]
avatar.enabled = false

# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"

[author]
name = "Your Name"
email = "your@email.com"
bio = "Your bio here"
image = "images/author.jpg"

[social]
  [[social.main]]
    name = "twitter"
    icon = "fab fa-twitter"
    link = "https://twitter.com/"
  [[social.main]]
    name = "github"
    icon = "fab fa-github"
    link = "https://github.com/"
  [[social.main]]
    name = "linkedin"
    icon = "fab fa-linkedin"
    link = "https://linkedin.com/"
